version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:mysql1234@db:3306/conf_users
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql1234
      MYSQL_DATABASE: conf_users
    ports:
      - "3307:3306"  # Change the external port to 3307
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysql1234
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
